# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image:
        required: true
        description: 'docker image name'
      sha-tag:
        required: true
        description: 'docker image tag'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: TEST

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.image }}
      
      - name: kustomize edit
        if: ${{ github.event.inputs.image }}
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          cd sealed 
          kustomize edit set image ${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }}
          rm -f kustomize
      
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        if: ${{ github.event.inputs.image }}
        with:
          repository: https://github.com/mafeifan/flask-demo-kustomize.git
          token: ${{ secrets.MY_SECRET_TOKEN }}
          force: true
          message: "kustomize set image to ${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }}"
